### ISSUE TITLE
WebSocket connection fails

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#42]
After 1.5 - 2 minutes, the WebSocket connection fails with the following exception:

```
[08-10 16:20:33.829][DSLink][ERROR] Exception processing message from web socket:
System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.Sockets.SocketException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DSLink.Connection.WebSocketConnector.<<_startReceiveTask>b__10_0>d.MoveNext().
```

**Comment by mbreissi** [comment]
Further information: this error does not seem to occur when using the SDK in a pure .Net Core 2.0 application.  However, it does occur when you attempt to use the SDK in an application that targets a .Net Framework 4.6 or later application.  It is easily reproducible with the ExampleDSLink contained in the SDK.

This is a major issue as many of the third party libraries available for external systems (industrial protocols, historians, etc.) are based on .Net Framework and thus links for those system must be as well.

**Comment by mbreissi** [comment]
Switched to an open source web socket client implementation instead of using the System.net.WebSockets client and everything works well when used in .net framework applications.  Presumptive conclusion is a bug exists in the Microsoft framework.  Suggest filing an issue with Microsoft and using an alternate in the SDK in the interim.  I used websocket-sharp, which is available via NuGet.

**Comment by mbreissi** [comment]
Not sure that would be the case but it's possible.  I did create a stripped down test client that doesn't use the SDK apart from initial http handshake.  For the web socket processing, I simply receive and send the keep alive messages in a hard coded fashion without using any of the SDK support.  In that test, it still fails.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've implemented changes to address this issue, tested, and validated.  Please let us know if this change addresses this issue.
